package com.aslmk.authenticationservice.exception;

public enum ErrorCode {
    INTERNAL_ERROR,
    TWO_FACTOR_TOKEN_NOT_FOUND,
    TWO_FACTOR_TOKEN_EXPIRED,
    PASSWORD_RESET_TOKEN_NOT_FOUND,
    PASSWORD_RESET_TOKEN_EXPIRED,
    PROVIDER_NOT_FOUND,
    BAD_REQUEST,
    VERIFICATION_TOKEN_NOT_FOUND,
    VERIFICATION_TOKEN_EXPIRED,
    BAD_CREDENTIALS,
    USERNAME_NOT_FOUND,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    FIELD_VALIDATION_FAILED,
    RECAPTCHA_VALIDATION_FAILED
}
